// Code generated by protoc-gen-go. DO NOT EDIT.
// source: irreparabledb.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PutIrrSegResponse_Status int32

const (
	PutIrrSegResponse_FAIL PutIrrSegResponse_Status = 0
	PutIrrSegResponse_OK   PutIrrSegResponse_Status = 1
)

var PutIrrSegResponse_Status_name = map[int32]string{
	0: "FAIL",
	1: "OK",
}
var PutIrrSegResponse_Status_value = map[string]int32{
	"FAIL": 0,
	"OK":   1,
}

func (x PutIrrSegResponse_Status) String() string {
	return proto.EnumName(PutIrrSegResponse_Status_name, int32(x))
}
func (PutIrrSegResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_irreparabledb_3d8f7333dc3b68c4, []int{2, 0}
}

type GetIrrSegReponse_Status int32

const (
	GetIrrSegReponse_FAIL GetIrrSegReponse_Status = 0
	GetIrrSegReponse_OK   GetIrrSegReponse_Status = 1
)

var GetIrrSegReponse_Status_name = map[int32]string{
	0: "FAIL",
	1: "OK",
}
var GetIrrSegReponse_Status_value = map[string]int32{
	"FAIL": 0,
	"OK":   1,
}

func (x GetIrrSegReponse_Status) String() string {
	return proto.EnumName(GetIrrSegReponse_Status_name, int32(x))
}
func (GetIrrSegReponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_irreparabledb_3d8f7333dc3b68c4, []int{4, 0}
}

type DeleteIrrSegResponse_Status int32

const (
	DeleteIrrSegResponse_FAIL DeleteIrrSegResponse_Status = 0
	DeleteIrrSegResponse_OK   DeleteIrrSegResponse_Status = 1
)

var DeleteIrrSegResponse_Status_name = map[int32]string{
	0: "FAIL",
	1: "OK",
}
var DeleteIrrSegResponse_Status_value = map[string]int32{
	"FAIL": 0,
	"OK":   1,
}

func (x DeleteIrrSegResponse_Status) String() string {
	return proto.EnumName(DeleteIrrSegResponse_Status_name, int32(x))
}
func (DeleteIrrSegResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_irreparabledb_3d8f7333dc3b68c4, []int{6, 0}
}

// RmtSegInfo is info about a single  stored in the irreparable db
type RmtSegInfo struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val                  []byte   `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	LostPiecesCount      int64    `protobuf:"varint,3,opt,name=lost_pieces_count,json=lostPiecesCount,proto3" json:"lost_pieces_count,omitempty"`
	RepairUnixSec        int64    `protobuf:"varint,4,opt,name=repair_unix_sec,json=repairUnixSec,proto3" json:"repair_unix_sec,omitempty"`
	RepairAttemptCount   int64    `protobuf:"varint,6,opt,name=repair_attempt_count,json=repairAttemptCount,proto3" json:"repair_attempt_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RmtSegInfo) Reset()         { *m = RmtSegInfo{} }
func (m *RmtSegInfo) String() string { return proto.CompactTextString(m) }
func (*RmtSegInfo) ProtoMessage()    {}
func (*RmtSegInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_irreparabledb_3d8f7333dc3b68c4, []int{0}
}
func (m *RmtSegInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RmtSegInfo.Unmarshal(m, b)
}
func (m *RmtSegInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RmtSegInfo.Marshal(b, m, deterministic)
}
func (dst *RmtSegInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RmtSegInfo.Merge(dst, src)
}
func (m *RmtSegInfo) XXX_Size() int {
	return xxx_messageInfo_RmtSegInfo.Size(m)
}
func (m *RmtSegInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RmtSegInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RmtSegInfo proto.InternalMessageInfo

func (m *RmtSegInfo) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *RmtSegInfo) GetVal() []byte {
	if m != nil {
		return m.Val
	}
	return nil
}

func (m *RmtSegInfo) GetLostPiecesCount() int64 {
	if m != nil {
		return m.LostPiecesCount
	}
	return 0
}

func (m *RmtSegInfo) GetRepairUnixSec() int64 {
	if m != nil {
		return m.RepairUnixSec
	}
	return 0
}

func (m *RmtSegInfo) GetRepairAttemptCount() int64 {
	if m != nil {
		return m.RepairAttemptCount
	}
	return 0
}

// PutIrrSegRequest is a request message for the Put rpc call
type PutIrrSegRequest struct {
	Info                 *RmtSegInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	APIKey               []byte      `protobuf:"bytes,2,opt,name=APIKey,proto3" json:"APIKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PutIrrSegRequest) Reset()         { *m = PutIrrSegRequest{} }
func (m *PutIrrSegRequest) String() string { return proto.CompactTextString(m) }
func (*PutIrrSegRequest) ProtoMessage()    {}
func (*PutIrrSegRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_irreparabledb_3d8f7333dc3b68c4, []int{1}
}
func (m *PutIrrSegRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutIrrSegRequest.Unmarshal(m, b)
}
func (m *PutIrrSegRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutIrrSegRequest.Marshal(b, m, deterministic)
}
func (dst *PutIrrSegRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutIrrSegRequest.Merge(dst, src)
}
func (m *PutIrrSegRequest) XXX_Size() int {
	return xxx_messageInfo_PutIrrSegRequest.Size(m)
}
func (m *PutIrrSegRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutIrrSegRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutIrrSegRequest proto.InternalMessageInfo

func (m *PutIrrSegRequest) GetInfo() *RmtSegInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *PutIrrSegRequest) GetAPIKey() []byte {
	if m != nil {
		return m.APIKey
	}
	return nil
}

// PutIrrSegResponse is a response message for the Put rpc call
type PutIrrSegResponse struct {
	Info                 *RmtSegInfo              `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               PutIrrSegResponse_Status `protobuf:"varint,2,opt,name=status,proto3,enum=irreparabledb.PutIrrSegResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *PutIrrSegResponse) Reset()         { *m = PutIrrSegResponse{} }
func (m *PutIrrSegResponse) String() string { return proto.CompactTextString(m) }
func (*PutIrrSegResponse) ProtoMessage()    {}
func (*PutIrrSegResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_irreparabledb_3d8f7333dc3b68c4, []int{2}
}
func (m *PutIrrSegResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutIrrSegResponse.Unmarshal(m, b)
}
func (m *PutIrrSegResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutIrrSegResponse.Marshal(b, m, deterministic)
}
func (dst *PutIrrSegResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutIrrSegResponse.Merge(dst, src)
}
func (m *PutIrrSegResponse) XXX_Size() int {
	return xxx_messageInfo_PutIrrSegResponse.Size(m)
}
func (m *PutIrrSegResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutIrrSegResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutIrrSegResponse proto.InternalMessageInfo

func (m *PutIrrSegResponse) GetInfo() *RmtSegInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *PutIrrSegResponse) GetStatus() PutIrrSegResponse_Status {
	if m != nil {
		return m.Status
	}
	return PutIrrSegResponse_FAIL
}

// GetIrrSegRequest is a request message for the Get rpc call
type GetIrrSegRequest struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	APIKey               []byte   `protobuf:"bytes,2,opt,name=APIKey,proto3" json:"APIKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIrrSegRequest) Reset()         { *m = GetIrrSegRequest{} }
func (m *GetIrrSegRequest) String() string { return proto.CompactTextString(m) }
func (*GetIrrSegRequest) ProtoMessage()    {}
func (*GetIrrSegRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_irreparabledb_3d8f7333dc3b68c4, []int{3}
}
func (m *GetIrrSegRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIrrSegRequest.Unmarshal(m, b)
}
func (m *GetIrrSegRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIrrSegRequest.Marshal(b, m, deterministic)
}
func (dst *GetIrrSegRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIrrSegRequest.Merge(dst, src)
}
func (m *GetIrrSegRequest) XXX_Size() int {
	return xxx_messageInfo_GetIrrSegRequest.Size(m)
}
func (m *GetIrrSegRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIrrSegRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetIrrSegRequest proto.InternalMessageInfo

func (m *GetIrrSegRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *GetIrrSegRequest) GetAPIKey() []byte {
	if m != nil {
		return m.APIKey
	}
	return nil
}

// GetIrrSegReponse is a response message for the Get rpc call
type GetIrrSegReponse struct {
	Info                 *RmtSegInfo             `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               GetIrrSegReponse_Status `protobuf:"varint,2,opt,name=status,proto3,enum=irreparabledb.GetIrrSegReponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetIrrSegReponse) Reset()         { *m = GetIrrSegReponse{} }
func (m *GetIrrSegReponse) String() string { return proto.CompactTextString(m) }
func (*GetIrrSegReponse) ProtoMessage()    {}
func (*GetIrrSegReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_irreparabledb_3d8f7333dc3b68c4, []int{4}
}
func (m *GetIrrSegReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIrrSegReponse.Unmarshal(m, b)
}
func (m *GetIrrSegReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIrrSegReponse.Marshal(b, m, deterministic)
}
func (dst *GetIrrSegReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIrrSegReponse.Merge(dst, src)
}
func (m *GetIrrSegReponse) XXX_Size() int {
	return xxx_messageInfo_GetIrrSegReponse.Size(m)
}
func (m *GetIrrSegReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIrrSegReponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetIrrSegReponse proto.InternalMessageInfo

func (m *GetIrrSegReponse) GetInfo() *RmtSegInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *GetIrrSegReponse) GetStatus() GetIrrSegReponse_Status {
	if m != nil {
		return m.Status
	}
	return GetIrrSegReponse_FAIL
}

// DeleteRequest is a request message for the Delete rpc call
type DeleteIrrSegRequest struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	APIKey               []byte   `protobuf:"bytes,2,opt,name=APIKey,proto3" json:"APIKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteIrrSegRequest) Reset()         { *m = DeleteIrrSegRequest{} }
func (m *DeleteIrrSegRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteIrrSegRequest) ProtoMessage()    {}
func (*DeleteIrrSegRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_irreparabledb_3d8f7333dc3b68c4, []int{5}
}
func (m *DeleteIrrSegRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteIrrSegRequest.Unmarshal(m, b)
}
func (m *DeleteIrrSegRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteIrrSegRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteIrrSegRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteIrrSegRequest.Merge(dst, src)
}
func (m *DeleteIrrSegRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteIrrSegRequest.Size(m)
}
func (m *DeleteIrrSegRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteIrrSegRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteIrrSegRequest proto.InternalMessageInfo

func (m *DeleteIrrSegRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *DeleteIrrSegRequest) GetAPIKey() []byte {
	if m != nil {
		return m.APIKey
	}
	return nil
}

// DeleteIrrSegResponse is a response message for the Delete rpc call
type DeleteIrrSegResponse struct {
	Info                 *RmtSegInfo                 `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               DeleteIrrSegResponse_Status `protobuf:"varint,2,opt,name=status,proto3,enum=irreparabledb.DeleteIrrSegResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *DeleteIrrSegResponse) Reset()         { *m = DeleteIrrSegResponse{} }
func (m *DeleteIrrSegResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteIrrSegResponse) ProtoMessage()    {}
func (*DeleteIrrSegResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_irreparabledb_3d8f7333dc3b68c4, []int{6}
}
func (m *DeleteIrrSegResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteIrrSegResponse.Unmarshal(m, b)
}
func (m *DeleteIrrSegResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteIrrSegResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteIrrSegResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteIrrSegResponse.Merge(dst, src)
}
func (m *DeleteIrrSegResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteIrrSegResponse.Size(m)
}
func (m *DeleteIrrSegResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteIrrSegResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteIrrSegResponse proto.InternalMessageInfo

func (m *DeleteIrrSegResponse) GetInfo() *RmtSegInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *DeleteIrrSegResponse) GetStatus() DeleteIrrSegResponse_Status {
	if m != nil {
		return m.Status
	}
	return DeleteIrrSegResponse_FAIL
}

func init() {
	proto.RegisterType((*RmtSegInfo)(nil), "irreparabledb.RmtSegInfo")
	proto.RegisterType((*PutIrrSegRequest)(nil), "irreparabledb.PutIrrSegRequest")
	proto.RegisterType((*PutIrrSegResponse)(nil), "irreparabledb.PutIrrSegResponse")
	proto.RegisterType((*GetIrrSegRequest)(nil), "irreparabledb.GetIrrSegRequest")
	proto.RegisterType((*GetIrrSegReponse)(nil), "irreparabledb.GetIrrSegReponse")
	proto.RegisterType((*DeleteIrrSegRequest)(nil), "irreparabledb.DeleteIrrSegRequest")
	proto.RegisterType((*DeleteIrrSegResponse)(nil), "irreparabledb.DeleteIrrSegResponse")
	proto.RegisterEnum("irreparabledb.PutIrrSegResponse_Status", PutIrrSegResponse_Status_name, PutIrrSegResponse_Status_value)
	proto.RegisterEnum("irreparabledb.GetIrrSegReponse_Status", GetIrrSegReponse_Status_name, GetIrrSegReponse_Status_value)
	proto.RegisterEnum("irreparabledb.DeleteIrrSegResponse_Status", DeleteIrrSegResponse_Status_name, DeleteIrrSegResponse_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IrrSegDBClient is the client API for IrrSegDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IrrSegDBClient interface {
	// Put a db entry for the provided segment info
	Put(ctx context.Context, in *PutIrrSegRequest, opts ...grpc.CallOption) (*PutIrrSegResponse, error)
}

type irrSegDBClient struct {
	cc *grpc.ClientConn
}

func NewIrrSegDBClient(cc *grpc.ClientConn) IrrSegDBClient {
	return &irrSegDBClient{cc}
}

func (c *irrSegDBClient) Put(ctx context.Context, in *PutIrrSegRequest, opts ...grpc.CallOption) (*PutIrrSegResponse, error) {
	out := new(PutIrrSegResponse)
	err := c.cc.Invoke(ctx, "/irreparabledb.IrrSegDB/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IrrSegDBServer is the server API for IrrSegDB service.
type IrrSegDBServer interface {
	// Put a db entry for the provided segment info
	Put(context.Context, *PutIrrSegRequest) (*PutIrrSegResponse, error)
}

func RegisterIrrSegDBServer(s *grpc.Server, srv IrrSegDBServer) {
	s.RegisterService(&_IrrSegDB_serviceDesc, srv)
}

func _IrrSegDB_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutIrrSegRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IrrSegDBServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/irreparabledb.IrrSegDB/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IrrSegDBServer).Put(ctx, req.(*PutIrrSegRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IrrSegDB_serviceDesc = grpc.ServiceDesc{
	ServiceName: "irreparabledb.IrrSegDB",
	HandlerType: (*IrrSegDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _IrrSegDB_Put_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "irreparabledb.proto",
}

func init() { proto.RegisterFile("irreparabledb.proto", fileDescriptor_irreparabledb_3d8f7333dc3b68c4) }

var fileDescriptor_irreparabledb_3d8f7333dc3b68c4 = []byte{
	// 396 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x41, 0x8f, 0x9a, 0x50,
	0x14, 0x85, 0xfb, 0x84, 0x10, 0x73, 0x5b, 0x2b, 0x3e, 0x4d, 0x43, 0xdd, 0xd4, 0xb0, 0xb0, 0xc6,
	0xa4, 0xa6, 0xb1, 0xdb, 0xa6, 0x46, 0x6b, 0xda, 0x12, 0x9b, 0x94, 0x40, 0xbb, 0x68, 0x37, 0x04,
	0xe8, 0xd5, 0x90, 0x22, 0x50, 0xde, 0xc3, 0xe8, 0x8f, 0x99, 0xcc, 0x6a, 0xfe, 0xc2, 0xfc, 0xbe,
	0x09, 0x0f, 0x92, 0x19, 0x70, 0xcc, 0x44, 0x77, 0x7a, 0xee, 0x39, 0xe7, 0xf2, 0xf1, 0x1e, 0xd0,
	0x0d, 0xd2, 0x14, 0x13, 0x37, 0x75, 0xbd, 0x10, 0xff, 0x7a, 0x93, 0x24, 0x8d, 0x79, 0x4c, 0x5b,
	0x15, 0x51, 0xbf, 0x25, 0x00, 0xd6, 0x96, 0xdb, 0xb8, 0x31, 0xa2, 0x75, 0x4c, 0x55, 0x90, 0xfe,
	0xe1, 0x41, 0x23, 0x03, 0x32, 0x7a, 0x61, 0xe5, 0x3f, 0x73, 0x65, 0xe7, 0x86, 0x5a, 0xa3, 0x50,
	0x76, 0x6e, 0x48, 0xc7, 0xd0, 0x09, 0x63, 0xc6, 0x9d, 0x24, 0x40, 0x1f, 0x99, 0xe3, 0xc7, 0x59,
	0xc4, 0x35, 0x69, 0x40, 0x46, 0x92, 0xd5, 0xce, 0x07, 0xa6, 0xd0, 0x3f, 0xe7, 0x32, 0x1d, 0x42,
	0x3b, 0xdf, 0x16, 0xa4, 0x4e, 0x16, 0x05, 0x7b, 0x87, 0xa1, 0xaf, 0xc9, 0xc2, 0xd9, 0x2a, 0xe4,
	0x5f, 0x51, 0xb0, 0xb7, 0xd1, 0xa7, 0xef, 0xa1, 0x57, 0xfa, 0x5c, 0xce, 0x71, 0x9b, 0xf0, 0xb2,
	0x56, 0x11, 0x66, 0x5a, 0xcc, 0xe6, 0xc5, 0x48, 0x34, 0xeb, 0xbf, 0x41, 0x35, 0x33, 0x6e, 0xa4,
	0xa9, 0x8d, 0x1b, 0x0b, 0xff, 0x67, 0xc8, 0x38, 0x7d, 0x07, 0x72, 0x10, 0xad, 0x63, 0xf1, 0xf8,
	0xcf, 0xa7, 0xaf, 0x27, 0x55, 0xfe, 0x7b, 0x4c, 0x4b, 0xd8, 0xe8, 0x2b, 0x50, 0xe6, 0xa6, 0xb1,
	0xc2, 0x43, 0x49, 0x57, 0xfe, 0xd3, 0xaf, 0x09, 0x74, 0x1e, 0x74, 0xb3, 0x24, 0x8e, 0x18, 0x9e,
	0x5b, 0x3e, 0x03, 0x85, 0x71, 0x97, 0x67, 0x4c, 0x94, 0xbf, 0x9c, 0xbe, 0xad, 0x05, 0x8e, 0x16,
	0x4c, 0x6c, 0x61, 0xb7, 0xca, 0x98, 0xde, 0x07, 0xa5, 0x50, 0x68, 0x13, 0xe4, 0x2f, 0x73, 0xe3,
	0xbb, 0xfa, 0x8c, 0x2a, 0xd0, 0xf8, 0xb1, 0x52, 0x89, 0xfe, 0x11, 0xd4, 0xaf, 0x58, 0x83, 0x3f,
	0x3e, 0xba, 0x53, 0x7c, 0x57, 0xa4, 0x12, 0xbf, 0x08, 0xef, 0x53, 0x0d, 0x6f, 0x58, 0x0b, 0xd4,
	0xfb, 0xcf, 0xa1, 0x9b, 0x41, 0x77, 0x89, 0x21, 0x72, 0xbc, 0x14, 0xf0, 0x86, 0x40, 0xaf, 0xda,
	0x70, 0xd9, 0x19, 0x2e, 0x6a, 0x90, 0xe3, 0x5a, 0xe0, 0xb1, 0x1d, 0x67, 0x80, 0x4e, 0x7f, 0x42,
	0xb3, 0x08, 0x2f, 0x17, 0xf4, 0x1b, 0x48, 0x66, 0xc6, 0xe9, 0x9b, 0xd3, 0xd7, 0x44, 0xbc, 0x85,
	0xfe, 0xe0, 0xa9, 0x7b, 0xb4, 0x90, 0xff, 0x34, 0x12, 0xcf, 0x53, 0xc4, 0xe7, 0xfe, 0xe1, 0x2e,
	0x00, 0x00, 0xff, 0xff, 0xaa, 0xa4, 0x45, 0xf5, 0x05, 0x04, 0x00, 0x00,
}
